### ISSUE TITLE
Will not launch

### ISSUE THREAD

**Issue by BetaPotato** [JusticePro/SpigotGUI-Remastered#1]
The program does not show any GUI. Launching with 'java -jar "SpigotGUI Remastered 1.0.jar"' gives the following error:
```
java.io.FileNotFoundException: theme (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at me.justicepro.spigotgui.Core.SpigotGUI.loadTheme(SpigotGUI.java:2047)
        at me.justicepro.spigotgui.Core.SpigotGUI$1.run(SpigotGUI.java:131)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

Before uninstalling all java versions, reinstalling the java 11 and 8 jdks, and rebooting, I would get this error:
```
Error: opening registry key 'Software\JavaSoft\JRE'
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
```
This is version 1.0 Downloaded on 11/15/18 from the [spigotmc.org](https://www.spigotmc.org/resources/spigotgui-remastered.62417/) page.

**Comment by JusticePro** [comment]
Thank you. This issue has been solved!
